// mostly generated by claude 3.5 sonnet

#pragma once

#include "TimingProfiler.cuh"
#include "imgui.h"
#include <string>

class ProfilerGui {
public:
  ProfilerGui();
  void render();

private:
  float timeRange; // Time range to display in seconds
  ImGuiWindowFlags windowFlags;

  // UI constants
  static constexpr float ROW_HEIGHT = 24.0f;
  static constexpr float TIMELINE_HEIGHT = 150.0f;

  // Performance thresholds (in milliseconds)
  static constexpr float GOOD_THRESHOLD = 1.0f;  // Green if under 1ms
  static constexpr float WARN_THRESHOLD = 5.0f;  // Yellow at 5ms
  static constexpr float BAD_THRESHOLD = 16.67f; // Red at 16.67ms (60 FPS)

  // Render components
  void renderControls();
  void renderTimeline();
  void renderStatistics();

  // Helper functions
  ImU32 getColorForDuration(float duration) const;
};
