// mostly generated by claude 3.5 sonnet

#pragma once

#include "timing_profiler.cuh"
#include "imgui.h"

#include <string>

class ProfilerGui {
public:
  ProfilerGui();
  void render();

private:
  float time_range; // Time range to display in seconds
  ImGuiWindowFlags window_flags;

  // UI constants
  static constexpr float ROW_HEIGHT = 24.0f;
  static constexpr float TIMELINE_HEIGHT = 150.0f;

  // Performance thresholds (in milliseconds)
  static constexpr float GOOD_THRESHOLD = 1.0f;  // Green if under 1ms
  static constexpr float WARN_THRESHOLD = 5.0f;  // Yellow at 5ms
  static constexpr float BAD_THRESHOLD = 16.67f; // Red at 16.67ms (60 FPS)

  // Render components
  void render_controls();
  void render_timeline();
  void render_statistics();

  // Helper functions
  ImU32 get_color_for_duration(float duration) const;
};
