// mostly generated by claude 3.5 sonnet

#pragma once

#include <cuda_runtime.h>

#include <chrono>
#include <deque>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

class ProfilePoint {
public:
  struct Measurement {
    double timestamp; // Time since profiler start
    double duration;  // in milliseconds
  };

  ProfilePoint(const std::string &name,
               std::chrono::high_resolution_clock::time_point profiler_start_time);
  ~ProfilePoint();

  void start_measurement();
  void end_measurement();
  void enable() {
    enabled = true;
  }
  void disable() {
    enabled = false;
  }
  bool is_enabled() const {
    return enabled;
  }

  // Stats getters
  double get_last_duration() const {
    return !measurements.empty() ? measurements.back().duration : 0.0;
  }
  double get_average_duration() const;
  double get_min_duration() const;
  double get_max_duration() const;
  size_t get_sample_count() const {
    return measurements.size();
  }

  // Get measurements within the last N seconds
  std::vector<Measurement> get_recent_measurements(double seconds) const;

private:
  std::string name;
  bool enabled{true};
  bool active{false};

  // CPU timing
  std::chrono::high_resolution_clock::time_point cpu_start_time;
  std::chrono::high_resolution_clock::time_point profiler_start_time;

  // GPU timing
  cudaEvent_t start_event{};
  cudaEvent_t stop_event{};

  std::deque<Measurement> measurements;
  mutable std::mutex mutex;

  static constexpr size_t MAX_MEASUREMENTS = 1000;
  void trim_measurements();
};

class TimingProfiler {
public:
  static TimingProfiler &get_instance() {
    static TimingProfiler instance;
    return instance;
  }

  // RAII measurement helper
  class ScopedMeasurement {
  public:
    ScopedMeasurement(const std::string &name, TimingProfiler &profiler)
        : name(name), profiler(profiler) {
      profiler.start_measurement(name);
    }

    ~ScopedMeasurement() {
      profiler.end_measurement(name);
    }

  private:
    std::string name;
    TimingProfiler &profiler;
  };

  // Main API
  void start_measurement(const std::string &name);
  void end_measurement(const std::string &name);
  ScopedMeasurement scoped_measure(const std::string &name) {
    return ScopedMeasurement(name, *this);
  }

  // Profile point management
  void enable_point(const std::string &name);
  void disable_point(const std::string &name);
  bool is_point_enabled(const std::string &name) const;

  // Data access
  std::shared_ptr<ProfilePoint> get_point(const std::string &name);
  std::vector<std::string> get_profile_point_names() const;

  // Get profiler start time for relative timestamps
  std::chrono::high_resolution_clock::time_point get_start_time() const {
    return start_time;
  }

  // Reset all measurements
  void reset();

private:
  TimingProfiler();
  ~TimingProfiler() = default;
  TimingProfiler(const TimingProfiler &) = delete;
  TimingProfiler &operator=(const TimingProfiler &) = delete;

  mutable std::mutex mutex;
  std::unordered_map<std::string, std::shared_ptr<ProfilePoint>> points;
  std::chrono::high_resolution_clock::time_point start_time;
};
