// mostly generated by claude 3.5 sonnet

#include "timing_profiler.cuh"

#include <algorithm>
#include <limits>

ProfilePoint::ProfilePoint(const std::string &name,
                           std::chrono::high_resolution_clock::time_point profiler_start_time)
    : name(name), profiler_start_time(profiler_start_time) {
  cudaEventCreate(&start_event);
  cudaEventCreate(&stop_event);
}

ProfilePoint::~ProfilePoint() {
  cudaEventDestroy(start_event);
  cudaEventDestroy(stop_event);
}

void ProfilePoint::start_measurement() {
  std::lock_guard<std::mutex> lock(mutex);
  if (!enabled || active)
    return;

  cpu_start_time = std::chrono::high_resolution_clock::now();
  cudaEventRecord(start_event); // Records in default stream
  active = true;
}

void ProfilePoint::end_measurement() {
  std::lock_guard<std::mutex> lock(mutex);
  if (!enabled || !active)
    return;

  cudaEventRecord(stop_event); // Records in default stream

  // Get CPU time first
  auto cpu_end_time = std::chrono::high_resolution_clock::now();
  auto cpu_duration =
      std::chrono::duration<double, std::milli>(cpu_end_time - cpu_start_time).count();

  // Get GPU time
  cudaEventSynchronize(stop_event); // Wait for GPU work to complete
  float gpu_milliseconds = 0.0f;
  cudaEventElapsedTime(&gpu_milliseconds, start_event, stop_event);

  // Use the longer of CPU or GPU time as the actual duration
  auto duration = std::max(cpu_duration, static_cast<double>(gpu_milliseconds));

  auto timestamp = std::chrono::duration<double>(cpu_end_time - profiler_start_time).count();

  measurements.push_back({timestamp, duration});
  trim_measurements();
  active = false;
}

void ProfilePoint::trim_measurements() {
  while (measurements.size() > MAX_MEASUREMENTS) {
    measurements.pop_front();
  }
}

double ProfilePoint::get_average_duration() const {
  std::lock_guard<std::mutex> lock(mutex);
  if (measurements.empty())
    return 0.0;

  double sum = 0.0;
  for (const auto &m : measurements) {
    sum += m.duration;
  }
  return sum / measurements.size();
}

double ProfilePoint::get_min_duration() const {
  std::lock_guard<std::mutex> lock(mutex);
  if (measurements.empty())
    return 0.0;

  return std::min_element(
             measurements.begin(), measurements.end(),
             [](const Measurement &a, const Measurement &b) { return a.duration < b.duration; })
      ->duration;
}

double ProfilePoint::get_max_duration() const {
  std::lock_guard<std::mutex> lock(mutex);
  if (measurements.empty())
    return 0.0;

  return std::max_element(
             measurements.begin(), measurements.end(),
             [](const Measurement &a, const Measurement &b) { return a.duration < b.duration; })
      ->duration;
}

std::vector<ProfilePoint::Measurement> ProfilePoint::get_recent_measurements(double seconds) const {
  std::lock_guard<std::mutex> lock(mutex);
  if (measurements.empty())
    return {};

  double current_time = measurements.back().timestamp;
  double cutoff_time = current_time - seconds;

  auto it =
      std::find_if(measurements.rbegin(), measurements.rend(), [cutoff_time](const Measurement &m) {
        return m.timestamp < cutoff_time;
      }).base();

  return std::vector<Measurement>(it, measurements.end());
}

// TimingProfiler implementation
TimingProfiler::TimingProfiler() : start_time(std::chrono::high_resolution_clock::now()) {}

void TimingProfiler::start_measurement(const std::string &name) {
  std::lock_guard<std::mutex> lock(mutex);
  auto &point = points[name];
  if (!point) {
    point = std::make_shared<ProfilePoint>(name, start_time);
  }
  point->start_measurement();
}

void TimingProfiler::end_measurement(const std::string &name) {
  std::lock_guard<std::mutex> lock(mutex);
  if (auto it = points.find(name); it != points.end()) {
    it->second->end_measurement();
  }
}

void TimingProfiler::enable_point(const std::string &name) {
  std::lock_guard<std::mutex> lock(mutex);
  if (auto it = points.find(name); it != points.end()) {
    it->second->enable();
  }
}

void TimingProfiler::disable_point(const std::string &name) {
  std::lock_guard<std::mutex> lock(mutex);
  if (auto it = points.find(name); it != points.end()) {
    it->second->disable();
  }
}

bool TimingProfiler::is_point_enabled(const std::string &name) const {
  std::lock_guard<std::mutex> lock(mutex);
  if (auto it = points.find(name); it != points.end()) {
    return it->second->is_enabled();
  }
  return false;
}

std::shared_ptr<ProfilePoint> TimingProfiler::get_point(const std::string &name) {
  std::lock_guard<std::mutex> lock(mutex);
  if (auto it = points.find(name); it != points.end()) {
    return it->second;
  }
  return nullptr;
}

std::vector<std::string> TimingProfiler::get_profile_point_names() const {
  std::lock_guard<std::mutex> lock(mutex);
  std::vector<std::string> names;
  names.reserve(points.size());
  for (const auto &[name, _] : points) {
    names.push_back(name);
  }
  return names;
}

void TimingProfiler::reset() {
  std::lock_guard<std::mutex> lock(mutex);
  points.clear();
  start_time = std::chrono::high_resolution_clock::now();
}
